[package]
name = "hapcli-rdp-helper"
edition.workspace = true
license.workspace = true
version.workspace = true

[features]
default = []

[dependencies]
cpal = "0.16"
ironrdp = { git = "https://github.com/AnalyseDeCircuit/IronRDP", rev = "78b5ad91711f830cf20c842c1c0062e81c51db07", features = ["cliprdr", "connector", "displaycontrol", "dvc", "graphics", "input", "pdu", "rdpsnd", "session", "svc"] }
ironrdp-cliprdr-format = { git = "https://github.com/AnalyseDeCircuit/IronRDP", rev = "78b5ad91711f830cf20c842c1c0062e81c51db07" }
ironrdp-core = { git = "https://github.com/AnalyseDeCircuit/IronRDP", rev = "78b5ad91711f830cf20c842c1c0062e81c51db07" }
ironrdp-displaycontrol = { git = "https://github.com/AnalyseDeCircuit/IronRDP", rev = "78b5ad91711f830cf20c842c1c0062e81c51db07" }
ironrdp-egfx = { git = "https://github.com/AnalyseDeCircuit/IronRDP", rev = "78b5ad91711f830cf20c842c1c0062e81c51db07", features = ["openh264-libloading"] }
ironrdp-graphics = { git = "https://github.com/AnalyseDeCircuit/IronRDP", rev = "78b5ad91711f830cf20c842c1c0062e81c51db07" }
ironrdp-tls = { git = "https://github.com/AnalyseDeCircuit/IronRDP", rev = "78b5ad91711f830cf20c842c1c0062e81c51db07", default-features = false, features = ["native-tls"] }
ironrdp-tokio = { git = "https://github.com/AnalyseDeCircuit/IronRDP", rev = "78b5ad91711f830cf20c842c1c0062e81c51db07", features = ["reqwest"] }
native-tls = { version = "0.2", features = ["vendored"] }
hapcli-pcm-audio = { path = "../hapcli-pcm-audio" }
hapcli-remote-desktop = { path = "../hapcli-remote-desktop" }
semver = "1"
sha2 = "0.10"
smallvec = "1"
tokio.workspace = true
uuid.workspace = true
x509-cert = "0.2"
zeroize.workspace = true

[dev-dependencies]
tempfile = "3"
