[package]
name = "hapcli-plugin-registry"
edition.workspace = true
version.workspace = true

[dependencies]
hapcli-ai = { path = "../hapcli-ai" }
hapcli-network-proxy = { path = "../hapcli-network-proxy" }
hapcli-plugin-manifest = { path = "../hapcli-plugin-manifest" }
hapcli-plugin-protocol = { path = "../hapcli-plugin-protocol" }
reqwest.workspace = true
serde_json.workspace = true
sha2.workspace = true
zip.workspace = true
